pyproject: update py-build-cmake to 0.0.15
GitHub Actions test builds are now encountering the error:
ModuleNotFoundError: No module named 'tomli'
The latest py-build-cmake explicitly depends on tomli for Python<3.11.